#!/bin/bash

# creating secret rndc.key
# openssl rand -base64 15

: ${BIND_RNDCKEY:="D9yVnKTEXtrdHA=="}
: ${BIND_DIRECTORY:="/var/cache/bind/"}
: ${BIND_DNSSECVALIDATION:="auto"}
: ${BIND_DNSSECENABLE:="false"}
: ${BIND_VERSION:="none"}

CONFIGS_VARS=(
  BIND_RNDCKEY
  BIND_DIRECTORY
  BIND_DNSSECVALIDATION
  BIND_DNSSECENABLE
  BIND_VERSION
)

echo -n "==> Setting config vars ... "
for c in ${CONFIGS_VARS[@]}
do
  sed -i "s,@@${c}@@,$(eval echo \$${c})," /etc/bind/rndc.key
  sed -i "s,@@${c}@@,$(eval echo \$${c})," /etc/bind/named.conf.options
done
echo "Done"

echo "==> Starting bind9"
named -g -u bind -c /etc/bind/named.conf
