#!/bin/bash

# creating secret rndc.key
# openssl rand -base64 15

: ${BIND_RNDCKEY:="D9yVnKTEXtrdHA=="}

CONFIGS_VARS=(
  BIND_RNDCKEY
)

echo -n "==> Setting config vars ... "
for c in ${CONFIGS_VARS[@]}
do
  sed -i "s,@@${c}@@,$(eval echo \$${c})," /etc/bind/rndc.key
done
echo "Done"

echo "==> Starting bind9"
named -g -u bind -c /etc/bind/named.conf
