#!/bin/bash

# creating secret rndc.key
# openssl rand -base64 15

: ${BIND_RNDCKEY:="D9yVnKTEXtrdHA=="}
: ${BIND_DIRECTORY:="/var/cache/bind/"}
: ${BIND_DNSSECVALIDATION:="auto"}
: ${BIND_DNSSECENABLE:="false"}
: ${BIND_VERSION:="none"}
: ${BIND_LISTENONPORT:="53"}
: ${BIND_LISTENON:="any"}
: ${BIND_LISTENONPORTV6:="53"}
: ${BIND_LISTENONV6:="none"}
: ${BIND_AUTOMATICINTERFACESCAN:="yes"}
: ${BIND_ALLOWNEWZONES:="no"}
: ${BIND_FLUSHZONESONSHUTDOWN:="no"}
: ${BIND_GEOIPUSERECS:="yes"}
: ${BIND_ROOTKEYSENTINEL:="yes"}
: ${BIND_MESSAGECOMPRESSION:="yes"}
: ${BIND_MINIMALRESPONSES:="no"}
: ${BIND_MINIMALANY:="no"}
: ${BIND_NOTIFY:="yes"}
: ${BIND_RECURSION:="yes"}
: ${BIND_REQUESTNSID:="no"}

CONFIGS_VARS=(
  BIND_RNDCKEY
  BIND_DIRECTORY
  BIND_DNSSECVALIDATION
  BIND_DNSSECENABLE
  BIND_VERSION
  BIND_LISTENONPORT
  BIND_LISTENON
  BIND_LISTENONPORTV6
  BIND_LISTENONV6
  BIND_AUTOMATICINTERFACESCAN
  BIND_ALLOWNEWZONES
  BIND_FLUSHZONESONSHUTDOWN
  BIND_GEOIPUSERECS
  BIND_ROOTKEYSENTINEL
  BIND_MESSAGECOMPRESSION
  BIND_MINIMALRESPONSES
  BIND_MINIMALANY
  BIND_NOTIFY
  BIND_RECURSION
  BIND_REQUESTNSID
)

echo -n "==> Setting config vars ... "
for c in ${CONFIGS_VARS[@]}
do
  sed -i "s,@@${c}@@,$(eval echo \$${c})," /etc/bind/rndc.key
  sed -i "s,@@${c}@@,$(eval echo \$${c})," /etc/bind/named.conf.options
done
echo "Done"

echo "==> Starting bind9"
named -g -u bind -c /etc/bind/named.conf
